version: '3.3'
services:
  synapse:
     image: "matrixdotorg/synapse:latest"
     container_name: "synapse"
     volumes:
        - "./data:/data"
     environment:
        - VIRTUAL_HOST: ${VIRTUAL_HOST}
        - VIRTUAL_PORT: ${VIRTUAL_PORT}
        - LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
        - SYNAPSE_SERVER_NAME: ${SYNAPSE_SERVER_NAME}
        - SYNAPSE_REPORT_STATS: ${SYNAPSE_REPORT_STATS}
      networks: ["server"]
networks:
   server:
      external: true
